In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.linear_model import LinearRegression

In [3]:
Data=pd.read_csv("Dataframe.csv")

In [13]:
Data.drop(Data.loc[1,:])

Unnamed: 0      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0               0   221900.0         3       1.00         1180      5650   
2               2   180000.0         2       1.00          770     10000   
3               3   604000.0         4       3.00         1960      5000   
4               4   510000.0         3       2.00         1680      8080   
5               5  1225000.0         4       4.50         5420    101930   
...           ...        ...       ...        ...          ...       ...   
21608       21608   360000.0         3       2.50         1530      1131   
21609       21609   400000.0         4       2.50         2310      5813   
21610       21610   402101.0         2       0.75         1020      1350   
21611       21611   400000.0         3       2.50         1600      2388   
21612       21612   325000.0         2       0.75         1020      1076   

       floors  waterfront  view  condition  grade  sqft_above  sqft_basement  \
0         1.0           0     0          3      7        1180              0   
2         1.0           0     0          3      6         770              0   
3         1.0           0     0          5      7        1050            910   
4         1.0           0     0          3      8        1680              0   
5         1.0           0     0          3     11        3890           1530   
...       ...         ...   ...        ...    ...         ...            ...   
21608     3.0           0     0          3      8        1530              0   
21609     2.0           0     0          3      8        2310              0   
21610     2.0           0     0          3      7        1020              0   
21611     2.0           0     0          3      8        1600              0   
21612     2.0           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
5          2001             0    98053  47.6561 -122.005           4760   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15  
0            5650  
2            8062  
3            5000  
4            7503  
5          101930  
...           ...  
21608        1509  
21609        7200  
21610        2007  
21611        1287  
21612        1357  

[21612 rows x 20 columns]

In [20]:
y=np.array(Data.price).reshape(-1,1)

In [21]:
x=np.array(Data.drop('price',axis=1))

In [22]:
x.shape,y.shape

((21613, 19), (21613, 1))

In [23]:
kf=KFold(n_splits=3)

In [29]:
indices=list(kf.split(x))

In [31]:
indices[2]

(array([    0,     1,     2, ..., 14406, 14407, 14408]),
 array([14409, 14410, 14411, ..., 21610, 21611, 21612]))

In [27]:
i=1

for train,test in kf.split(x):
    print("\nTrain"+str(i),train)
    print("\nTest",test)
    i+=1


Train1 [ 7205  7206  7207 ... 21610 21611 21612]

Test [   0    1    2 ... 7202 7203 7204]

Train2 [    0     1     2 ... 21610 21611 21612]

Test [ 7205  7206  7207 ... 14406 14407 14408]

Train3 [    0     1     2 ... 14406 14407 14408]

Test [14409 14410 14411 ... 21610 21611 21612]


In [28]:
len(x),len(train),len(test)

(21613, 14409, 7204)

In [33]:
x_train1,y_train1=x[indices[0][0]],y[indices[0][0]]
x_train2,y_train2=x[indices[1][0]],y[indices[1][0]]

x_test1,y_test1=x[indices[0][1]],y[indices[0][1]]
x_test2,y_test2=x[indices[1][1]],y[indices[1][1]]


In [34]:
x_train1.shape

(14408, 19)

In [35]:
x_test1.shape

(7205, 19)

In [36]:
y_train1.shape

(14408, 1)

In [37]:
regressor=LinearRegression()
regressor.fit(x_train1,y_train1)
regressor.score(x_test1,y_test1)

0.7223994834143604

In [38]:
regressor.fit(x_train2,y_train2)
regressor.score(x_test2,y_test2)

0.7193375283268654

In [41]:
cross_val_score(regressor,x,y,cv=3)

array([0.72239948, 0.71933753, 0.72291521])

In [42]:
from sklearn.model_selection  import RepeatedKFold

In [47]:
rep_kf=RepeatedKFold(n_splits=2,n_repeats=2,random_state=40)

In [48]:
indices=list(rep_kf.split(x))
print(indices)

[(array([    0,     4,     7, ..., 21603, 21606, 21608]), array([    1,     2,     3, ..., 21610, 21611, 21612])), (array([    1,     2,     3, ..., 21610, 21611, 21612]), array([    0,     4,     7, ..., 21603, 21606, 21608])), (array([    0,     1,     9, ..., 21604, 21608, 21611]), array([    2,     3,     4, ..., 21609, 21610, 21612])), (array([    2,     3,     4, ..., 21609, 21610, 21612]), array([    0,     1,     9, ..., 21604, 21608, 21611]))]


In [49]:
i=1

for train,test in rep_kf.split(x):
    print("\nTrain"+str(i),train)
    print("\nTest",test)
    i+=1


Train1 [    0     4     7 ... 21603 21606 21608]

Test [    1     2     3 ... 21610 21611 21612]

Train2 [    1     2     3 ... 21610 21611 21612]

Test [    0     4     7 ... 21603 21606 21608]

Train3 [    0     1     9 ... 21604 21608 21611]

Test [    2     3     4 ... 21609 21610 21612]

Train4 [    2     3     4 ... 21609 21610 21612]

Test [    0     1     9 ... 21604 21608 21611]


In [50]:
regressor.fit(x_train1,y_train1)
regressor.score(x_test1,y_test1)

0.7223994834143604

In [51]:
regressor.fit(x_train2,y_train2)
regressor.score(x_test2,y_test2)

0.7193375283268654

In [52]:
cross_val_score(regressor,x,y,cv=rep_kf)

array([0.7291084 , 0.72141872, 0.73004319, 0.71750949])

In [53]:
from sklearn.linear_model import LogisticRegression

In [70]:
logistic=LogisticRegression(solver='liblinear')

TypeError: __init__() got an unexpected keyword argument 'c'

In [55]:
from sklearn.model_selection import StratifiedKFold

In [72]:
cancer_data=pd.read_csv('cancer_data.csv')

In [84]:
cancer_data=cancer_data.drop(['Unnamed: 0','Diagnosis'],axis=1)

In [85]:
x=cancer_data.drop('Outcome',axis=1)

In [86]:
y=cancer_data['Outcome']

In [87]:
skf=StratifiedKFold(n_splits=5,shuffle=True)

In [88]:
indices=list(skf.split(x,y))

In [89]:
indices

[(array([  0,   2,   3,   4,   5,   6,   9,  10,  11,  12,  13,  14,  15,
          16,  17,  18,  19,  20,  23,  24,  25,  26,  27,  28,  29,  30,
          33,  34,  35,  36,  38,  39,  41,  42,  43,  44,  45,  47,  48,
          51,  52,  53,  55,  56,  57,  59,  60,  62,  63,  64,  65,  67,
          68,  69,  71,  72,  73,  74,  75,  77,  78,  79,  80,  81,  82,
          83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  95,  96,  97,
          98, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
         113, 114, 115, 116, 117, 118, 119, 121, 122, 124, 125, 126, 127,
         129, 131, 132, 133, 134, 135, 137, 138, 139, 141, 142, 143, 144,
         146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159,
         160, 161, 162, 163, 164, 167, 169, 170, 171, 173, 174, 175, 176,
         178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 192,
         193, 195, 196, 198, 200, 201, 202, 203, 205, 206, 207, 208, 209,
         211, 212, 213, 215, 216, 219,

In [90]:
x_train1,y_train1=x.loc[indices[0][0]],y.loc[indices[0][0]]
x_train2,y_train2=x.loc[indices[1][0]],y.loc[indices[1][0]]

x_test1,y_test1=x.loc[indices[0][1]],y.loc[indices[0][1]]
x_test2,y_test2=x.loc[indices[1][1]],y.loc[indices[1][1]]

In [91]:
x_train1.shape

(614, 8)

In [92]:
logistic.fit(x_train1,y_train1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [93]:
logistic.score(x_test1,y_test1)

0.7207792207792207

In [94]:
logistic.fit(x_train2,y_train2)
logistic.score(x_test2,y_test2)

0.8116883116883117